spring:
  application:
    name: model-management-service
  config:
    import:
    - "optional:configserver:http://config-server:9000"
  cloud:
    config:
      cache:
        enabled: true
        cache-type: hazelcast  # Or another caching implementation (e.g., caffeine)
        cache-names: config 
        
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - env
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultUrl: http://localhost:8091/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}